export const uiCopy = {
  common: {
    unexpectedError: 'Ocorreu um erro inesperado. Tente novamente.',
  },
  auth: {
    loginTitle: 'Acesse sua conta',
    registerTitle: 'Crie sua conta',
    sessionError: 'Não foi possível validar sua sessão. Faça login novamente.',
    loginFormError: 'Não foi possível entrar. Verifique seus dados e tente novamente.',
    registerFormError: 'Não foi possível criar sua conta. Tente novamente.',
    signingIn: 'Entrando...',
    creatingAccount: 'Criando conta...',
    loginPrompt: 'Não tem uma conta?',
    registerPrompt: 'Já tem uma conta?',
    loginCta: 'Entrar',
    registerCta: 'Cadastre-se',
  },
  navigation: {
    features: 'Funcionalidades',
    howItWorks: 'Como funciona',
    testimonials: 'Depoimentos',
    pricing: 'Preços',
    login: 'Entrar',
    logout: 'Sair',
    viewPlans: 'Ver planos',
    story: 'Nossa história',
    account: 'Conta',
    backToDashboard: 'Voltar ao painel',
    plans: 'Planos',
    demo: 'Experimentar',
    settingsAriaLabel: 'Configurações da conta',
  },
  story: {
    notFoundTitle: 'Link não encontrado',
    notFoundDescription: 'Esta história não foi encontrada.',
    loadErrorTitle: 'Não foi possível abrir a história',
    loadErrorDescription: 'Não foi possível carregar esta história agora. Tente novamente em instantes.',
    privateTitle: 'História protegida',
    privateDescription: 'Digite a senha para continuar.',
    passwordPlaceholder: 'Senha',
    passwordRequired: 'Informe a senha para continuar.',
    passwordInvalid: 'Não foi possível validar a senha. Tente novamente.',
    saveSuccess: 'Sua história foi salva com sucesso.',
    saveError: 'Não foi possível salvar sua história agora. Tente novamente em instantes.',
    shareTitle: 'Compartilhe sua história',
    shareDescription: 'Baixe o QR Code ou compartilhe o link diretamente.',
    downloadSuccess: 'QR Code baixado com sucesso!',
    shareSuccess: 'Link compartilhado com sucesso.',
    copySuccess: 'Link copiado para a área de transferência.',
    shareError: 'Não foi possível compartilhar o link.',
    copyError: 'Não foi possível copiar o link.',
    enterButton: 'Entrar na história',
    backToEditor: 'Voltar ao editor',
  },
  dashboard: {
    shareReadyTitle: 'Sua história está no ar.',
    shareReadyDescription: 'Use as opções abaixo para ver uma prévia ou compartilhar o link.',
    shareUpgradeDescription: 'Faça upgrade para compartilhar sua história com o mundo.',
    preview: 'Ver prévia',
    share: 'Compartilhar',
    upgrade: 'Fazer upgrade',
    editMode: 'Modo de edição',
    welcome: 'Bem-vindo(a),',
    draftDescription: 'Sua história de amor ainda não foi criada. Preencha os detalhes abaixo para começar.',
    editModeDescription: 'Faça as alterações que desejar na sua história.',
    loadError: 'Não foi possível carregar sua história agora. Tente novamente em instantes.',
    saveError: 'Não foi possível salvar sua história agora. Tente novamente em instantes.',
    saveSuccess: 'Sua história foi salva com sucesso.',
    summaryTitle: 'Eternizando cada segundo',
    editStory: 'Editar história',
    previewTitle: 'Nossa história de amor',
    backToEditor: 'Voltar ao editor',
    previewPlaceholder: 'A pré-visualização aparecerá aqui.',
  },
  account: {
    title: 'Configurações da conta',
    description: 'Gerencie suas informações e seu plano.',
    detailsTitle: 'Seus dados',
    currentPlanLabel: 'Plano atual',
    noPlanActive: 'Nenhum plano ativo',
    nameLabel: 'Nome',
    emailLabel: 'E-mail',
    logout: 'Sair da conta',
  },
  editor: {
    title: 'Editor da história',
    contentSection: 'Conteúdo principal',
    mediaSection: 'Mídia e aparência',
    accessSection: 'Configurações de acesso',
    startedWhen: 'Quando tudo começou?',
    messageLabel: 'Deixe uma mensagem surpresa',
    messagePlaceholder: 'Escreva algo especial aqui...',
    photosLabel: 'Fotos de vocês',
    addPhoto: 'Adicionar foto',
    positionLabel: 'Posição do contador',
    top: 'Superior',
    center: 'Centro',
    bottom: 'Inferior',
    youtubeLabel: 'Música do YouTube (opcional)',
    youtubePlaceholder: 'Cole o link do YouTube aqui',
    passwordLabel: 'Senha da história (opcional)',
    passwordPlaceholderKeep: 'Digite uma nova senha ou deixe em branco para manter',
    passwordPlaceholderSet: 'Digite para definir ou alterar',
    passwordHelper: 'Se este campo ficar vazio, a senha atual será mantida. Marque abaixo para removê-la.',
    removePassword: 'Remover senha atual',
    entryButtonLabel: 'Texto do botão de entrada (opcional)',
    entryButtonPlaceholder: 'Ex.: Entrar, ver nossa história...',
    save: 'Salvar história',
    saving: 'Salvando...',
    saveAndShare: 'Salvar e compartilhar',
    cancel: 'Cancelar',
    imageItem: 'Imagem',
    upgradeTitle: 'Clique para fazer upgrade',
    imageLimitMessage: (limit: number) => `Você atingiu o limite de ${limit} imagem(ns). Faça upgrade para adicionar mais.`,
    youtubeUpgradeMessage: 'Adicione uma música de fundo do YouTube à sua história.',
    passwordUpgradeMessage: 'Proteja sua história com uma senha.',
    customButtonUpgradeMessage: 'Personalize o texto do botão de entrada da sua história.',
    previewPanelTitle: 'Prévia da história',
  },
  payment: {
    checkoutUnavailable: 'Não foi possível carregar o checkout agora. Tente novamente em instantes.',
    redirectingCheckout: 'Redirecionando para o checkout...',
    processing: 'Processando seu pagamento...',
    planLabel: 'Plano',
    totalLabel: 'Total',
    cardholderPlaceholder: 'Nome e sobrenome',
    cardExpirationPlaceholder: 'MM/AA',
    securityCodePlaceholder: 'CVC',
    documentPlaceholder: 'CPF ou CNPJ',
    cardBrandAlt: 'Bandeira',
    mercadoPagoAlt: 'Mercado Pago',
    successToast: 'Pagamento aprovado. Seu plano foi atualizado.',
    successTitle: 'Pagamento aprovado',
    successDescription: 'Sua compra foi concluída com sucesso. Seu plano já foi atualizado.',
    failureTitle: 'Pagamento não aprovado',
    failureDescription: 'Não foi possível concluir o pagamento. Verifique seus dados e tente novamente.',
    pendingTitle: 'Pagamento pendente',
    pendingDescription: 'Estamos aguardando a confirmação. Quando o pagamento for aprovado, seu plano será atualizado automaticamente.',
    formFieldError: 'Alguns dados do cartão estão incorretos.',
    genericError: 'Não foi possível processar o pagamento. Tente novamente.',
    createAccount: 'Crie sua conta para escolher um plano.',
    planNotFound: 'Plano não encontrado.',
    checkoutTitle: 'Checkout',
    processedBy: 'Processado por',
    pay: (amount: string) => `Pagar R$ ${amount}`,
    successButton: 'Ir para o painel',
    failureButton: 'Tentar novamente',
    pendingButton: 'Ir para o painel',
  },
  pricing: {
    titleLead: 'Um Legado Digital para o',
    titleHighlight: 'Seu Amor.',
    description: 'Escolha o plano perfeito para eternizar sua história e garantir que suas memórias durem para sempre.',
    loadError: 'Não foi possível carregar os planos agora. Tente novamente em instantes.',
    loading: 'Carregando...',
    currentPlanButton: 'Seu plano atual',
    upgradeButton: 'Fazer upgrade',
    downgradeButton: 'Mudar para este plano',
    popularBadge: 'Popular',
    currentBadge: 'Seu plano',
    oneTimePayment: 'Pagamento único',
    specialFeature: 'Pague uma vez, use para sempre',
  },
  marketing: {
    hero: {
      titleLead: 'A história de vocês merece ser',
      titleHighlight: 'eternizada.',
      description: 'Reúna os momentos mágicos do seu relacionamento em uma cápsula do tempo online, criada para celebrar o passado, o presente e o futuro de vocês.',
      cta: 'Construir nosso legado (grátis)',
    },
    demo: {
      titleLead: 'Teste ao vivo: crie sua própria',
      titleHighlight: 'prévia',
      description: 'Experimente agora mesmo como é fácil e divertido criar sua história de amor.',
    },
    features: {
      titleLead: 'O que torna sua história',
      titleHighlight: 'eternizada.',
      description: 'Cada detalhe, cuidadosamente pensado para transformar suas memórias em um tesouro que dura para sempre.',
      cta: 'Comece a criar sua história',
      cards: [
        {
          title: 'O Tempo do Nosso Amor',
          description: 'Veja o tempo do seu amor em movimento. Um contador que parte do primeiro segundo, celebra o agora e segue contando, rumo ao infinito.',
        },
        {
          title: 'Os Capítulos da Nossa História',
          description: 'Cada foto, uma página do seu livro de amor. Organize e reviva os capítulos da sua jornada, dos primeiros encontros às grandes conquistas.',
        },
        {
          title: 'A Melodia da Nossa História',
          description: 'Se a sua história de amor fosse uma canção, qual seria? Adicione a melodia que embala seus capítulos e dá o tom exato para cada momento.',
        },
      ],
    },
    howItWorks: {
      titleLead: 'Sua cápsula do tempo,',
      titleHighlight: 'em 3 passos.',
      description: 'Transformar suas memórias em um legado eterno é mais fácil do que você imagina.',
      cta: 'Dar o primeiro passo (grátis)',
      steps: [
        {
          title: 'Crie sua História',
          description: 'Defina a data que deu início a tudo e escreva a mensagem que será o coração da sua história eternizada.',
        },
        {
          title: 'Personalize',
          description: 'Dê vida à sua história com uma galeria de fotos, a trilha sonora de vocês e outros detalhes que a tornam única.',
        },
        {
          title: 'Compartilhe',
          description: 'É hora da surpresa! Compartilhe o link diretamente ou adicione um toque mágico ao seu presente físico com o QR Code exclusivo.',
        },
      ],
    },
    socialProof: {
      titleLead: 'Milhares de Histórias',
      titleHighlight: 'Eternizadas',
      description: 'Inspire-se com quem já transformou o amor em um legado digital.',
      cta: 'Construir nosso legado',
      testimonials: [
        {
          quote: 'Foi o presente mais emocionante que já recebi. Chorei quando vi o contador e nossas fotos passando com a nossa música. Incrível!',
          author: 'Juliana R.',
          detail: 'Cápsula do tempo para o namorado',
        },
        {
          quote: 'Achei que seria complicado, mas criei tudo em menos de 10 minutos pelo celular. A interface é linda e super fácil de usar.',
          author: 'Marcos T.',
          detail: 'Criou em 10 minutos pelo celular',
        },
        {
          quote: 'O resultado final é muito mais do que eu esperava. Parece um site profissional, super premium. Minha esposa amou.',
          author: 'Fernando P.',
          detail: 'Presente premium para a esposa',
        },
      ],
    },
    faq: {
      titleLead: 'Perguntas',
      titleHighlight: 'Frequentes',
      description: 'Tirando suas últimas dúvidas para que você possa criar seu presente com tranquilidade.',
      items: [
        {
          question: 'Preciso pagar para testar?',
          answer: 'Não! Você pode criar sua história, adicionar uma data, mensagem, uma foto e ver a pré-visualização de como ficará o presente. Tudo isso de graça e sem precisar de cadastro.',
        },
        {
          question: 'A pessoa que recebe o presente precisa pagar?',
          answer: 'Nunca. O acesso à história é sempre gratuito e ilimitado para quem recebe o link. Apenas quem cria a história precisa de um plano para poder compartilhá-la.',
        },
        {
          question: 'Meus dados e fotos estão seguros?',
          answer: 'Sim. Sua história só pode ser acessada através do link exclusivo gerado para você. Além disso, nossos planos pagos oferecem a opção de proteção por senha para uma camada extra de privacidade.',
        },
        {
          question: 'Posso editar a história depois de publicada?',
          answer: 'Sim! Com qualquer um dos nossos planos, você pode fazer login no seu painel a qualquer momento para adicionar mais fotos (de acordo com seu plano), alterar a mensagem, a música e muito mais.',
        },
      ],
    },
    finalCta: {
      titleLead: 'Sua história merece ser',
      titleHighlight: 'eternizada.',
      description: 'Não deixe o tempo apagar o que realmente importa. Comece a construir seu legado digital hoje mesmo.',
      cta: 'Construir nosso legado (grátis)',
    },
  },
} as const;
