BEGIN;

DELETE FROM public.app_config
WHERE key IN (
  'CHECKOUT_TYPE',
  'MERCADO_PAGO_ACCESS_TOKEN',
  'MERCADO_PAGO_PUBLIC_KEY',
  'MP_TEST_USER_EMAIL',
  'STRIPE_PUBLIC_KEY',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SIGNING_SECRET'
);

COMMIT;
